### ISSUE TITLE
HTMX foundations link goes to localhost:5001

### ISSUE THREAD

**Issue by chrisclark** [AnswerDotAI/fh-about#3]
For some reason on the [site](https://about.fastht.ml/tech#sec2), the link to HTMX foundations:
<img width="410" alt="image" src="https://github.com/user-attachments/assets/03579f68-2184-49d6-8c19-63f72b371e1d">

Goes to:
http://localhost:5001/foundation#sec2

Unclear to me why this is happening. The underlying code:
https://github.com/AnswerDotAI/fh-about/blob/main/tech.py#L53

Looks the same as eg. the link on this line:
https://github.com/AnswerDotAI/fh-about/blob/main/tech.py#L57

Which works fine.

**Comment by johnowhitaker** [comment]
This is a recent fix, @jph00 might need to deploy the latest version (when it's not midnight in Australia)

**Comment by jph00** [comment]
Thank you!
